/**
 * Portfolio image pipeline — `bun run images`
 *
 * Input  : portfolio-originals/<slug>/avant.(jpg|jpeg|png|webp|avif|tif)
 *          portfolio-originals/<slug>/apres.(jpg|jpeg|png|webp|avif|tif)
 * Output : public/images/portfolio/<slug>-avant-{800,1600}.webp
 *          public/images/portfolio/<slug>-apres-{800,1600}.webp
 *          src/data/portfolio-images.generated.ts  (dimensions per slug)
 *
 * Both photos of a pair are cropped to the same aspect ratio (the "après" one)
 * so they line up perfectly inside the before/after slider.
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import { join, parse } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const SOURCE_DIR = join(ROOT, 'portfolio-originals')
const OUTPUT_DIR = join(ROOT, 'public', 'images', 'portfolio')
const MANIFEST = join(ROOT, 'src', 'data', 'portfolio-images.generated.ts')
const WIDTHS = [800, 1600] as const
const EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.tif', '.tiff'])
const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
/** Keep extreme panoramas / tall shots usable in the slider. */
const MIN_RATIO = 4 / 5
const MAX_RATIO = 16 / 9

type Side = 'avant' | 'apres'

async function findSide(dir: string, side: Side): Promise<string | null> {
  const files = await readdir(dir)
  const match = files.find((file) => {
    const { name, ext } = parse(file)
    return name.toLowerCase() === side && EXTENSIONS.has(ext.toLowerCase())
  })
  return match ? join(dir, match) : null
}

async function orientedSize(path: string) {
  // `.rotate()` applies the EXIF orientation of phone photos.
  const { info } = await sharp(path).rotate().toBuffer({ resolveWithObject: true })
  return { width: info.width, height: info.height }
}

/**
 * Exports one side at each target width, never upscaling beyond `maxWidth`
 * (the smaller source width of the pair) so small photos stay sharp and light.
 */
async function exportSide(path: string, slug: string, side: Side, ratio: number, maxWidth: number) {
  for (const target of WIDTHS) {
    const width = Math.min(target, maxWidth)
    const height = Math.round(width / ratio)
    await sharp(path)
      .rotate()
      .resize(width, height, { fit: 'cover', position: sharp.strategy.attention })
      .webp({ quality: 74, effort: 5 })
      // Named by *target* width: the site always requests -800 / -1600.
      .toFile(join(OUTPUT_DIR, `${slug}-${side}-${target}.webp`))
  }
}

async function main() {
  const entries = await readdir(SOURCE_DIR, { withFileTypes: true }).catch(() => [])
  const slugs = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  if (slugs.length === 0) {
    console.error(`No project folders found in ${SOURCE_DIR}`)
    process.exit(1)
  }

  await rm(OUTPUT_DIR, { recursive: true, force: true })
  await mkdir(OUTPUT_DIR, { recursive: true })

  const manifest: Record<string, { width: number; height: number }> = {}
  const problems: string[] = []

  for (const slug of slugs) {
    if (!SLUG.test(slug)) {
      problems.push(
        `"${slug}": folder name must be lowercase-with-dashes (e.g. boulangerie-paris-11)`,
      )
      continue
    }
    const dir = join(SOURCE_DIR, slug)
    const before = await findSide(dir, 'avant')
    const after = await findSide(dir, 'apres')
    if (!before || !after) {
      problems.push(
        `"${slug}": needs both avant.* and apres.* (found ${[before, after].filter(Boolean).length}/2)`,
      )
      continue
    }

    const size = await orientedSize(after)
    const beforeSize = await orientedSize(before)
    const ratio = Math.min(MAX_RATIO, Math.max(MIN_RATIO, size.width / size.height))
    // Largest width both photos can provide once cropped to the shared ratio.
    const usable = (s: { width: number; height: number }) => Math.min(s.width, s.height * ratio)
    const maxWidth = Math.round(Math.min(usable(size), usable(beforeSize), 1600))
    await exportSide(before, slug, 'avant', ratio, maxWidth)
    await exportSide(after, slug, 'apres', ratio, maxWidth)
    manifest[slug] = { width: maxWidth, height: Math.round(maxWidth / ratio) }
    if (maxWidth < 1000) {
      console.log(
        `  ⚠ ${slug}: source photos are small (${maxWidth}px wide) — use the original phone photos for a sharper result`,
      )
    }
    console.log(`✓ ${slug}  (${manifest[slug].width}×${manifest[slug].height})`)
  }

  const body = Object.entries(manifest)
    .map(([slug, { width, height }]) => `  '${slug}': { width: ${width}, height: ${height} },`)
    .join('\n')
  await writeFile(
    MANIFEST,
    `// Generated by \`bun run images\` — do not edit by hand.\nexport const portfolioImages: Record<string, { width: number; height: number }> = {\n${body}\n}\n`,
  )

  if (problems.length > 0) {
    console.error(`\n${problems.length} folder(s) skipped:\n- ${problems.join('\n- ')}`)
    process.exit(1)
  }
  console.error(`\nDone: ${Object.keys(manifest).length} project(s) → public/images/portfolio`)
}

await main()
