// Generated by `bun run images` — do not edit by hand.
export const portfolioImages: Record<string, { width: number; height: number }> = {
  'artisan-pique': { width: 470, height: 588 },
  'cer-monceau': { width: 470, height: 588 },
  'feeling-musique': { width: 647, height: 809 },
  'permis-en-accelere': { width: 470, height: 588 },
}
